### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [mhavril39/my_new_app#1]
Looking mostly very good. I love the use of SCSS! There are just a couple things I'd like you to fix.

The first is that one that one of the criteria isn't _quite_ fulfilled yet:

> have well-labeled links to all of the above routes on all pages of the app, using path helpers and **without repeating code**

The code for those links is repeated on every page. To DRY this up, let's extract it out to [our layout file](https://github.com/mhavril39/my_new_app/blob/master/app/views/layouts/application.html.erb).

The second thing I'd like the SCSS file updated to use two-space soft-tabs like you're using in the rest of the project. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by mhavril39** [comment]
Hi Chris,

Made the changes you asked for and I finally figured out the spacing! Thanks.

Mike

Quoting Chris Fritz notifications@github.com:

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
